openapi: 3.0.2
info:
  title: TransferZero Account Debits API Logs API
  description: Reference documentation for the TransferZero API V1
  version: '1.0'
servers:
- url: https://api-sandbox.transferzero.com/v1
- url: https://api.transferzero.com/v1
security:
- AuthorizationKey: []
  AuthorizationNonce: []
  AuthorizationSignature: []
- AuthorizationKey: []
  AuthorizationSecret: []
tags:
- name: API Logs
paths:
  /api_logs:
    get:
      tags:
      - API Logs
      summary: Fetch a list of API logs
      description: Returns a list of API logs. Also includes information relating to the original request.
      operationId: get-api-logs
      parameters:
      - name: page
        in: query
        description: The page number to request (defaults to 1)
        required: false
        schema:
          type: integer
        example: 1
      - name: per
        in: query
        description: The number of results to load per page (defaults to 10)
        required: false
        schema:
          type: integer
        example: 10
      - name: created_at_from
        in: query
        description: 'Start date to filter recipients by created_at range

          Allows filtering results by the specified `created_at` timeframe.


          Example: `/v1/recipients?created_at_from=2018-06-06&created_at_to=2018-06-08`'
        required: false
        schema:
          type: string
      - name: created_at_to
        in: query
        description: 'End date to filter recipients by created_at range

          Allows filtering results by the specified `created_at` timeframe.


          Example: `/v1/recipients?created_at_from=2018-06-06&created_at_to=2018-06-08`'
        required: false
        schema:
          type: string
      responses:
        '200':
          description: API logs returned within an array wrapped inside a JSON object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiLogListResponse'
        '401':
          description: Authentication information is missing or invalid.
        '500':
          description: Internal Server Error.
      x-group-parameters: true
  /api_logs/{API Log ID}:
    get:
      tags:
      - API Logs
      summary: Fetch an individual API log
      description: Returns a single API log based on the API log ID.
      operationId: get-api-log
      parameters:
      - name: API Log ID
        in: path
        description: 'ID of the API log to retrieve


          Example: `/v1/api_logs/00485ce9-532b-45e7-8518-7e5582242407`'
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Details of requested API log
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiLogResponse'
        '401':
          description: Authentication information is missing or invalid.
        '404':
          description: Resource Not Found.
        '500':
          description: Internal Server Error.
      x-group-parameters: true
components:
  schemas:
    ApiLogResponse:
      type: object
      properties:
        object:
          $ref: '#/components/schemas/ApiLog'
      readOnly: true
      example:
        object:
          response_headers:
            X-Frame-Options: SAMEORIGIN
            X-XSS-Protection: 1; mode=block
            X-Content-Type-Options: nosniff
            Content-Type: application/json; charset=UTF-8
          request_body: '{"message":"Email dispatched: Accepted (user@transferzero.com)"}'
          response_status: '200'
          request_headers:
            HTTP_VERSION: HTTP/1.1
            HTTP_ACCEPT: application/json
            HTTP_USER_AGENT: TransferZero Ruby
            HTTP_AUTHORIZATION_NONCE: '0000'
            HTTP_AUTHORIZATION_KEY: '0000'
            HTTP_AUTHORIZATION_SIGNATURE: '0000'
            HTTP_CONNECTION: close
            HTTP_HOST: localhost:3002
          response_body: '{"object":{"result":0}}'
          created_at: 2019-01-11T00:00:00.001+0000
          id: a0696374-de2f-4b4e-a2d7-cb4e0a1240c0
          request_method: POST
          request_url: https://api.transferzero/v1/transactions/validate
    ApiLogListResponse:
      type: object
      properties:
        object:
          type: array
          description: Array of API log objects
          readOnly: true
          items:
            $ref: '#/components/schemas/ApiLog'
        meta:
          $ref: '#/components/schemas/PaginationMeta'
      readOnly: true
      example:
        meta:
          pagination:
            next_page: 3
            total_count: 45
            total_pages: 5
            prev_page: 1
            current_page: 2
        object:
        - response_headers:
            X-Frame-Options: SAMEORIGIN
            X-XSS-Protection: 1; mode=block
            X-Content-Type-Options: nosniff
            Content-Type: application/json; charset=UTF-8
          request_body: '{"message":"Email dispatched: Accepted (user@transferzero.com)"}'
          response_status: '200'
          request_headers:
            HTTP_VERSION: HTTP/1.1
            HTTP_ACCEPT: application/json
            HTTP_USER_AGENT: TransferZero Ruby
            HTTP_AUTHORIZATION_NONCE: '0000'
            HTTP_AUTHORIZATION_KEY: '0000'
            HTTP_AUTHORIZATION_SIGNATURE: '0000'
            HTTP_CONNECTION: close
            HTTP_HOST: localhost:3002
          response_body: '{"object":{"result":0}}'
          created_at: 2019-01-11T00:00:00.001+0000
          id: a0696374-de2f-4b4e-a2d7-cb4e0a1240c0
          request_method: POST
          request_url: https://api.transferzero/v1/transactions/validate
        - response_headers:
            X-Frame-Options: SAMEORIGIN
            X-XSS-Protection: 1; mode=block
            X-Content-Type-Options: nosniff
            Content-Type: application/json; charset=UTF-8
          request_body: '{"message":"Email dispatched: Accepted (user@transferzero.com)"}'
          response_status: '200'
          request_headers:
            HTTP_VERSION: HTTP/1.1
            HTTP_ACCEPT: application/json
            HTTP_USER_AGENT: TransferZero Ruby
            HTTP_AUTHORIZATION_NONCE: '0000'
            HTTP_AUTHORIZATION_KEY: '0000'
            HTTP_AUTHORIZATION_SIGNATURE: '0000'
            HTTP_CONNECTION: close
            HTTP_HOST: localhost:3002
          response_body: '{"object":{"result":0}}'
          created_at: 2019-01-11T00:00:00.001+0000
          id: a0696374-de2f-4b4e-a2d7-cb4e0a1240c0
          request_method: POST
          request_url: https://api.transferzero/v1/transactions/validate
    PaginationMeta:
      type: object
      properties:
        pagination:
          $ref: '#/components/schemas/Pagination'
      readOnly: true
      example:
        pagination:
          next_page: 3
          total_count: 45
          total_pages: 5
          prev_page: 1
          current_page: 2
    ApiLog:
      type: object
      properties:
        id:
          type: string
          description: ID of the API log
          format: uuid
          readOnly: true
          example: a0696374-de2f-4b4e-a2d7-cb4e0a1240c0
        request_method:
          type: string
          description: Initial HTTP request method
          readOnly: true
          example: POST
        request_url:
          type: string
          description: URL to which initial request was sent
          readOnly: true
          example: https://api.transferzero/v1/transactions/validate
        request_body:
          type: string
          description: Body sent with initial request returned as a string
          readOnly: true
          example: '{"message":"Email dispatched: Accepted (user@transferzero.com)"}'
        request_headers:
          type: object
          additionalProperties:
            type: string
          description: Authorization and access information sent with initial request
          readOnly: true
          example:
            HTTP_VERSION: HTTP/1.1
            HTTP_ACCEPT: application/json
            HTTP_USER_AGENT: TransferZero Ruby
            HTTP_AUTHORIZATION_NONCE: '0000'
            HTTP_AUTHORIZATION_KEY: '0000'
            HTTP_AUTHORIZATION_SIGNATURE: '0000'
            HTTP_CONNECTION: close
            HTTP_HOST: localhost:3002
        response_status:
          type: string
          description: Status of response
          readOnly: true
          example: '200'
        response_body:
          type: string
          description: Full response body returned as a string
          readOnly: true
          example: '{"object":{"result":0}}'
        response_headers:
          type: object
          additionalProperties:
            type: string
          description: Headers returned with response
          readOnly: true
          example:
            X-Frame-Options: SAMEORIGIN
            X-XSS-Protection: 1; mode=block
            X-Content-Type-Options: nosniff
            Content-Type: application/json; charset=UTF-8
        created_at:
          type: string
          description: Date and time of response
          readOnly: true
          example: 2019-01-11T00:00:00.001+0000
      description: 'The response object returned with requests to access individual API logs

        '
      readOnly: true
      example:
        response_headers:
          X-Frame-Options: SAMEORIGIN
          X-XSS-Protection: 1; mode=block
          X-Content-Type-Options: nosniff
          Content-Type: application/json; charset=UTF-8
        request_body: '{"message":"Email dispatched: Accepted (user@transferzero.com)"}'
        response_status: '200'
        request_headers:
          HTTP_VERSION: HTTP/1.1
          HTTP_ACCEPT: application/json
          HTTP_USER_AGENT: TransferZero Ruby
          HTTP_AUTHORIZATION_NONCE: '0000'
          HTTP_AUTHORIZATION_KEY: '0000'
          HTTP_AUTHORIZATION_SIGNATURE: '0000'
          HTTP_CONNECTION: close
          HTTP_HOST: localhost:3002
        response_body: '{"object":{"result":0}}'
        created_at: 2019-01-11T00:00:00.001+0000
        id: a0696374-de2f-4b4e-a2d7-cb4e0a1240c0
        request_method: POST
        request_url: https://api.transferzero/v1/transactions/validate
    Pagination:
      type: object
      properties:
        current_page:
          type: integer
          description: The number of the current page
          readOnly: true
          example: 2
        next_page:
          type: integer
          description: The number of the next page. If no next page exists, this will be `null`
          readOnly: true
          example: 3
        prev_page:
          type: integer
          description: The number of the previous page. If no previous page exists, this will be `null`
          readOnly: true
          example: 1
        total_pages:
          type: integer
          description: The number of pages in the result set
          readOnly: true
          example: 5
        total_count:
          type: integer
          description: The total number of results in the set
          readOnly: true
          example: 45
      readOnly: true
      example:
        next_page: 3
        total_count: 45
        total_pages: 5
        prev_page: 1
        current_page: 2
  securitySchemes:
    AuthorizationKey:
      type: apiKey
      description: Please see the [Authentication guide](https://docs.transferzero.com/docs/authentication) on how to use these fields
      name: Authorization-Key
      in: header
    AuthorizationSecret:
      type: apiKey
      description: Please see the [Authentication guide](https://docs.transferzero.com/docs/authentication) on how to use these fields
      name: Authorization-Secret
      in: header
    AuthorizationNonce:
      type: apiKey
      description: Please see the [Authentication guide](https://docs.transferzero.com/docs/authentication) on how to use these fields
      name: Authorization-Nonce
      in: header
    AuthorizationSignature:
      type: apiKey
      description: Please see the [Authentication guide](https://docs.transferzero.com/docs/authentication) on how to use these fields
      name: Authorization-Signature
      in: header
externalDocs:
  description: API documentation and onboarding guide
  url: https://docs.transferzero.com/
